#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.2.3.1

PKG_DEPENDS=""
PKG_MAINTAINER="Jaroslav Kysela <perex@perex.cz>, et al"
PKG_SECTION="audio"
PKG_SHORTDESC="Advanced Linux Sound Architecture library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
