#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.26.3

PKG_DEPENDS="glib libXtst"
PKG_MAINTAINER="Mike Gorse <mgorse@novell.com>, et al"
PKG_SECTION="gnome"
PKG_SHORTDESC="AT SPI CORE"

buildpkg() {
   ../configure ${TARGET_CONFIGURE_OPTS} \
       LDFLAGS="$LDFLAGS -lxcb -lX11 -Wl,-rpath-link=$INSTALL_PATH/usr/lib"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
