#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.8

PKG_DEPENDS=""
PKG_MAINTAINER="Julian Seward<jseward@acm.org>"
PKG_SECTION="compress"
PKG_SHORTDESC="bzip2 data compressor"

buildpkg() {
  cp ../* .
  make -f Makefile-libbz2_so CC=${TARGET_PREFIX}gcc
  mkdir -p $INSTALL_PKG/usr/include $INSTALL_PKG/usr/lib
  ln -sf libbz2.so.$PKG_VERSION libbz2.so
  cp bzlib.h $INSTALL_PKG/usr/include
  cp -ar libbz2.so* $INSTALL_PKG/usr/lib
}
