#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.16.0

PKG_DEPENDS="glib fontconfig pixman libXext libXrender"
PKG_MAINTAINER="Bryce Harrington <bryce@osg.samsung.com>"
PKG_SECTION="graphics"
PKG_SHORTDESC="Multi-platform 2D graphics library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --enable-gobject \
      --enable-xlib
#      --enable-xlib-xrender 
#      --enable-xcb \
#      --enable-xlib-xcb \
#      --enable-xcb-shm \
#      --disable-glesv2 \
#      --disable-egl \
#      --disable-drm \
#      --enable-png \
#      --enable-ft \
#      --enable-fc \
#      --enable-ps \
#      --enable-pdf \
#      --enable-svg \
#      --enable-pthread

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
