#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.26.1

PKG_DEPENDS="gtk+ libxml2"
PKG_MAINTAINER="Ryan Lortie <desrt@desrt.ca>"
PKG_SECTION="gnome"
PKG_SHORTDESC="dconf is a simple key/value storage system that is heavily optimised for reading."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --disable-man \
      LDFLAGS="$LDFLAGS -luuid -Wl,-rpath-link=$INSTALL_PATH/usr/lib"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
