#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.8

PKG_DEPENDS=""
PKG_MAINTAINER="Dave Airlie <airlied@redhat.com>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="X.Org DRI2 protocol headers"

buildpkg() {
  TARGET_CONFIGURE_OPTS=$(echo ${TARGET_CONFIGURE_OPTS}|sed "s/aarch64-/arm-/")
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
