#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0

PKG_DEPENDS=""
PKG_MAINTAINER="Keith Packard <keithp@keithp.com>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="X.Org DRI3 protocol headers"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
