#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2018.76

PKG_DEPENDS="zlib"
PKG_MAINTAINER="Matt Johnston (matt@ucc.asn.au)"
PKG_SECTION="network"
PKG_SHORTDESC="A small SSH server and client."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
    --with-zlib=$INSTALL_PATH/usr

  make $MAKEFLAGS
  make scp
  make DESTDIR=$INSTALL_PKG install
  cp scp $INSTALL_PKG/usr/bin
}
