#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.12.8

PKG_DEPENDS="libxfce4ui"
PKG_MAINTAINER="Benedikt Meurer <benny@xfce.org>, et al"
PKG_SECTION="xfce4"
PKG_SHORTDESC="Libexo is an extension library to Xfce"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      LDFLAGS="$LDFLAGS -Wl,-rpath-link=$INSTALL_PATH/usr/lib -lxcb -lXau -luuid" \
      --disable-gtk2

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
