#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.2.9

PKG_DEPENDS=""
PKG_MAINTAINER="Expat maintainers"
PKG_SECTION="textproc"
PKG_SHORTDESC="XML parser library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --without-xmlwf

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
