#!/bin/bash

PKG_NAME=$1
PKG_VERSION=5.29

PKG_DEPENDS="zlib"
PKG_MAINTAINER="Christos Zoulas (christos@astron.com)"
PKG_SECTION="tools"
PKG_SHORTDESC="File type identification utility"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
