#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.3.3

PKG_DEPENDS="libogg"
PKG_MAINTAINER="Erik de Castro Lopo <erikd@mega-nerd.com>"
PKG_SECTION="audio"
PKG_SHORTDESC="A Free Lossless Audio Codec"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
