#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.1.3

PKG_DEPENDS=""
PKG_MAINTAINER="Julien Cristau <jcristau@debian.org>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="Fonts extension headers"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
