#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.10.1

PKG_DEPENDS="libpng"
PKG_MAINTAINER="David Turner, Robert Wilhelm, and Werner Lemberg"
PKG_SECTION="print"
PKG_SHORTDESC="TrueType font rendering library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
    --without-harfbuzz

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
