#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.9

PKG_DEPENDS=""
PKG_MAINTAINER="Behdad Esfahbod <behdad@gnu.org>"
PKG_SECTION="print"
PKG_SHORTDESC="The Bidirectional Algorithm library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
