#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.2.0

PKG_DEPENDS="ORBit2"
PKG_MAINTAINER="Havoc Pennington <hp@redhat.com>"
PKG_SECTION="gnome"
PKG_SHORTDESC="GConf is a system for storing application preferences."

buildpkg() {
  TARGET_CONFIGURE_OPTS=$(echo ${TARGET_CONFIGURE_OPTS}|sed "s/aarch64-/arm-/")
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --with-gtk=3.0

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
