#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.53.4

PKG_DEPENDS="dbus libffi zlib util-linux"
PKG_MAINTAINER="Hans Breuer <hans@breuer.org>"
PKG_SECTION="devel"
PKG_SHORTDESC="C support library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
    glib_cv_stack_grows=no \
    glib_cv_uscore=no \
    glib_cv_va_val_copy=no \
    ac_cv_func_mmap_fixed_mapped=yes \
    ac_cv_func_posix_getpwuid_r=yes \
    ac_cv_func_posix_getgrgid_r=yes \
    ac_cv_func_snprintf_c99=yes \
    ac_cv_func_vsnprintf_c99=yes \
    --disable-libmount \
    --with-pcre=internal \
    --with-threads=posix \
    LDFLAGS="$LDFLAGS -lffi" \

    #--disable-selinux \
    #--disable-dtrace \
    #--disable-systemtap \
    #--disable-fam \
    #--disable-libelf \
    #--with-python=/usr/bin/python \

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
