#!/bin/bash

PKG_NAME=$1
PKG_VERSION=6.2.0

PKG_DEPENDS=""
PKG_MAINTAINER="GNU.ORG"
PKG_SECTION="tools"
PKG_SHORTDESC="The GNU MP library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
