#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.32.2

PKG_DEPENDS="pcre2 dconf vte gsettings-desktop-schemas"
PKG_MAINTAINER="Guilherme de S. Pastore <gpastore@gnome.org>, et al"
PKG_SECTION="gnome"
PKG_SHORTDESC="A terminal emulator for GNOME."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --without-nautilus-extension \
      --disable-search-provider \
      LDFLAGS="$LDFLAGS -Wl,-rpath-link=$INSTALL_PATH/usr/lib"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
