#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.28.1

PKG_DEPENDS=""
PKG_MAINTAINER="Bastien Nocera<hadess@hadess.net>"
PKG_SECTION="gnome"
PKG_SHORTDESC="gsettings desktop schemas"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
