#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.8.3

PKG_DEPENDS="gtk+ enchant iso-codes"
PKG_MAINTAINER="Sébastien Wilmet <swilmet@gnome.org>"
PKG_SECTION="apps"
PKG_SHORTDESC="gspell provides a flexible API to add spell-checking to a GTK application."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      LDFLAGS="$LDFLAGS -Wl,-rpath-link=$INSTALL_PATH/usr/lib"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
