#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.6.0

PKG_DEPENDS=""
PKG_MAINTAINER="Scott Burleigh, JPL scott.c.burleigh@jpl.nasa.gov"
PKG_SECTION="network"
PKG_SHORTDESC="Library for Interplanetary Overlay Networks"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --with-expat \
      --disable-sysctl-check

  sed -i "s/-Werror//g" Makefile
  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
