#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.7

PKG_DEPENDS=""
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="KB extension headers"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
