#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.11

PKG_DEPENDS="fontconfig tiff"
PKG_MAINTAINER="Marti Maria Saguer"
PKG_SECTION="graphics"
PKG_SHORTDESC="Little CMS"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
