#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.4.100

PKG_DEPENDS=""
PKG_MAINTAINER="Rickard E. (Rik) Faith <faith@valinux.com>"
PKG_SECTION="graphics"
PKG_SHORTDESC="Userspace interface to kernel DRM services"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
    --disable-intel \
    --disable-radeon \
    --disable-amdgpu \
    --disable-udev \
    --disable-install-test-programs \
    --disable-cairo-tests \
    --disable-valgrind

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
