#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.5.3

PKG_DEPENDS="mesa"
PKG_MAINTAINER="Intel Corp."
PKG_SECTION="graphics"
PKG_SHORTDESC="A library for handling OpenGL function pointer management."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --enable-x11 \
      --disable-egl 

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
