#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.3

PKG_DEPENDS=""
PKG_MAINTAINER="Anthony Green<green@moxielogic.com>, etc."
PKG_SECTION="devel"
PKG_SHORTDESC="Foreign Function Interface Library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
