#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.3

PKG_DEPENDS="libusb"
PKG_MAINTAINER="Intra2net AG <opensource@intra2net.com>"
PKG_SECTION="network"
PKG_SHORTDESC="libFTDI is an open source library to talk to FTDI chips"

buildpkg() {
  cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_C_COMPILER=${TARGET_PREFIX}gcc \
    -DCMAKE_LINKER=${TARGET_PREFIX}ld \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DSHAREDLIBS=ON \
    -DSTATICLIBS=OFF \
    -DDOCUMENTATION=FALSE \
    -DEXAMPLES=FALSE \
    -DFTDIPP=FALSE \
    -DPYTHON_BINDINGS=FALSE
  
  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
