#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.36

PKG_DEPENDS=""
PKG_MAINTAINER="Werner Koch <wk@gnupg.org>"
PKG_SECTION="security"
PKG_SHORTDESC="Library that defines common error values for GnuPG components"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
