#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.8.6

PKG_DEPENDS="libgpg-error"
PKG_MAINTAINER="Werner Koch <wk@gnupg.org>"
PKG_SECTION="security"
PKG_SHORTDESC="General purpose cryptographic library."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --with-libgpg-error-prefix=$INSTALL_PATH/usr

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
