#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.10

PKG_DEPENDS="xtrans"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X Inter-Client Exchange (ICE) protocol library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
