#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.9.64

PKG_DEPENDS="curl"
PKG_MAINTAINER="Christian Grothoff <christian@grothoff.org>"
PKG_SECTION="network"
PKG_SHORTDESC="A small C library that is supposed to make it easy to run an HTTP server as part of another application."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --with-libgcrypt-prefix=$INSTALL_PATH/usr \
      LDFLAGS="$LDFLAGS -lcurl -Wl,-rpath-link=$INSTALL_PATH/usr/lib"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
