#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.4

PKG_DEPENDS=""
PKG_MAINTAINER="Pablo Neira Ayuso <pablo@netfilter.org>"
PKG_SECTION="network"
PKG_SHORTDESC="A minimalistic user-space library oriented to Netlink developers."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
