#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.1

PKG_DEPENDS=""
PKG_MAINTAINER="Thomas Graf <tgraf@suug.ch>"
PKG_SECTION="network"
PKG_SHORTDESC="Tiny replacement for libnl versions 1 and 2"

buildpkg() {
  cp ../* . -ar
  rm -rf include/linux
  make $MAKEFLAGS \
    CC=${TARGET_PREFIX}gcc \
    STATICLIB="" \
    prefix=/usr

  make DESTDIR=$INSTALL_PKG \
    CC=${TARGET_PREFIX}gcc \
    STATICLIB="" \
    prefix=/usr \
    install
}
