#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.3.4

PKG_DEPENDS=""
PKG_MAINTAINER="Monty <monty@xiph.org>,Greg Maxwell <greg@xiph.org>, et al"
PKG_SECTION="multimedia"
PKG_SHORTDESC="Open source bitstream container format"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
