#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.4

PKG_DEPENDS=""
PKG_MAINTAINER="Tom Tromey <tromey@cygnus.com>"
PKG_SECTION="devel"
PKG_SHORTDESC="A library providing weak aliases for pthread functions"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
