#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.40.5

PKG_DEPENDS="libcroco gdk-pixbuf pango"
PKG_MAINTAINER="Glenn Randers-Pehrson"
PKG_SECTION="gtk"
PKG_SHORTDESC="librsvg is a high performance SVG rendering library associated with the  Gnome Project. "

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
