#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.7.2

PKG_DEPENDS=""
PKG_MAINTAINER="Eric Young (eay@cryptsoft.com)"
PKG_SECTION="security"
PKG_SHORTDESC="A FREE version of the SSL/TLS protocol forked from OpenSSL"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
