#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.28

PKG_DEPENDS="alsa-lib"
PKG_MAINTAINER="Erik de Castro Lopo (erikd AT mega-nerd DOT com)"
PKG_SECTION="audio"
PKG_SHORTDESC="A library for accessing various audio file formats"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
