#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.20.1

PKG_DEPENDS="libgcrypt"
PKG_MAINTAINER="Stef Walter <stefw@collabora.co.uk>"
PKG_SECTION=""
PKG_SHORTDESC="GObject based library for accessing the Secret Service API. "

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --disable-manpages \
      --with-libgcrypt-prefix=$INSTALL_PATH/usr


  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
