#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.3.7

PKG_DEPENDS="libogg"
PKG_MAINTAINER="Monty <monty@xiph.org>, et al"
PKG_SECTION="audio"
PKG_SHORTDESC="Lossless audio compression tools using the ogg-vorbis algorithms"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
