#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.1.5

PKG_DEPENDS="libXfixes"
PKG_MAINTAINER="Keith Packard @HP, Eric Anholt @Intel"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X11 damaged region extension library."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
