#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.14.1

PKG_DEPENDS="gtk+ xfconf"
PKG_MAINTAINER="Benedikt Meurer <benny@xfce.org>"
PKG_SECTION="xfce4"
PKG_SHORTDESC="XFCE4 user interface library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      LDFLAGS="$LDFLAGS -Wl,-rpath-link=$INSTALL_PATH/usr/lib -lxcb -lXau" \
      --disable-gtk2

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
