#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.9.10

PKG_DEPENDS="libX11"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X Rendering Extension client library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --enable-malloc0returnsnull

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
