#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.3.3

PKG_DEPENDS="fontconfig libXrender"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X FreeType library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
