#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.1.3

PKG_DEPENDS="xorgproto"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X Display Manager Control Protocol library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
