#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.2.0

PKG_DEPENDS="libXext"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X-Resource extension client library."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --enable-malloc0returnsnull

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install 
}


