#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.3.4

PKG_DEPENDS="libX11"
PKG_MAINTAINER="Peter Hutterer <peter.hutterer@who-t.net>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X11 miscellaneous extensions library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --enable-malloc0returnsnull

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
