#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.5.2

PKG_DEPENDS="libXrender libXext"
PKG_MAINTAINER="Keith Packard <keithp@keithp.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X Resize, Rotate and Reflection extension client library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
    --enable-malloc0returnsnull

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install 
}
