#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.5.13

PKG_DEPENDS="libX11"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X Pixmap (XPM) image file format library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
