#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.2.0

PKG_DEPENDS="libX11 libSM"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X11 toolkit intrinsics library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
