#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.1.0

PKG_DEPENDS="libX11"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="X11 keyboard file manipulation library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
