#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.9.10

PKG_DEPENDS="zlib"
PKG_MAINTAINER="Daniel Veillard <daniel@veillard.com>, et al"
PKG_SECTION="textproc"
PKG_SHORTDESC="XML parser library for Gnome"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --without-lzma \
      --without-python

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
