#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.2.3

PKG_DEPENDS="libXi"
PKG_MAINTAINER="Alan Coopersmith <alan.coopersmith@oracle.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="Xlib-based client API for the XTEST & RECORD extensions."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
