#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.6.3

PKG_DEPENDS="libXmu"
PKG_MAINTAINER="Matt Turner <mattst88@gmail.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="The 3D Athena widget set"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
