#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.3

PKG_DEPENDS="xorgproto"
PKG_MAINTAINER="Keith Packard <keithp@keithp.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="Shared memory 'SyncFence' synchronization primitive."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
