#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.6.9

PKG_DEPENDS="libxcb xtrans"
PKG_MAINTAINER="Jim Gettys"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="The X11 library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
    --enable-malloc0returnsnull

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
