#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.1.0

PKG_DEPENDS="gmp"
PKG_MAINTAINER="GNU.ORG"
PKG_SECTION="tools"
PKG_SHORTDESC="The GNU MPC library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
