#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.3.1

PKG_DEPENDS="libjpeg-turbo"
PKG_MAINTAINER="Michael Adams"
PKG_SECTION="graphics"
PKG_SHORTDESC="JPEG-2000 Part-1 standard (i.e., ISO/IEC 15444-1) implementation"

buildpkg() {
  cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_PROCESSOR=${TARGET_ARCH}\
    -DCMAKE_C_COMPILER=${TARGET_PREFIX}gcc \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_STATIC=OFF

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
