#!/bin/bash

PKG_NAME=$1
PKG_VERSION=13.0

PKG_DEPENDS="libsndfile dbus systemd util-linux libressl libcap libtool"
PKG_MAINTAINER="Peter Meerwald <pmeerw@pmeerw.net>, et al"
PKG_SECTION="audio"
PKG_SHORTDESC="Yet another sound server for Unix"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --without-soxr \
      --without-caps \
      --disable-x11 \
      --disable-avahi \
      --disable-gtk3 \
      --disable-dbus \
      --disable-udev \
      LDFLAGS="$LDFLAGS -Wl,-rpath-link=$INSTALL_PATH/usr/lib -luuid"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
