#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.5.0

PKG_DEPENDS=""
PKG_MAINTAINER="Dave Airlie <airlied@redhat.com>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="Randr extension headers"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
