#!/bin/bash

PKG_NAME=$1
PKG_VERSION=8.0

PKG_DEPENDS=""
PKG_MAINTAINER="Chet Ramey <chet.ramey@case.edu>"
PKG_SECTION="devel"
PKG_SHORTDESC="Library that provides command-line editor."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
