#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.0.10

PKG_DEPENDS="libjpeg-turbo zlib"
PKG_MAINTAINER="Bob Friesenhahn <bfriesen@simple.dallas.tx.us>"
PKG_SECTION="graphics"
PKG_SHORTDESC="Library for reading and writing TIFF files"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
