#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.19.0

PKG_DEPENDS=""
PKG_MAINTAINER="Gaetan Nadon <memsize@videotron.ca>, et al"
PKG_SECTION="x11/util"
PKG_SHORTDESC="X.org autoconf utilities"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
