#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.16.3

PKG_DEPENDS="libjpeg-turbo"
PKG_MAINTAINER="Hans Verkuil <hverkuil@xs4all.nl>, et al."
PKG_SECTION="tools"
PKG_SHORTDESC="Linux V4L2 and DVB API utilities and v4l libraries (libv4l)."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --disable-libdvbv5 \
      --disable-v4l-utils \ 
      LIBS="-ljpeg"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
