#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.3.3

PKG_DEPENDS=""
PKG_MAINTAINER="Adam Jackson <ajax@redhat.com>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="video extension headers"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
