#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.14

PKG_DEPENDS=""
PKG_MAINTAINER="Bart Massey, Jamey Sharp, and Josh Triplett."
PKG_SECTION="x11/proto"
PKG_SHORTDESC="X C-language Bindings protocol headers"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
