#!/bin/bash

PKG_NAME=$1
PKG_VERSION=7.3.0

PKG_DEPENDS=""
PKG_MAINTAINER="Peter Hutterer <peter.hutterer@who-t.net>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="Xext extension headers"

buildpkg() {
   TARGET_CONFIGURE_OPTS=$(echo ${TARGET_CONFIGURE_OPTS}|sed "s/aarch64-/arm-/")
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
