#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.5.0

PKG_DEPENDS="xorg-server"
PKG_MAINTAINER="Julien Cristau <jcristau@debian.org>"
PKG_SECTION="x11/driver"
PKG_SHORTDESC="The Xorg driver for framebuffer driver"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
