#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.10.6

PKG_DEPENDS="xorg-server libevdev mtdev"
PKG_MAINTAINER="Peter Hutterer <peter.hutterer@who-t.net>"
PKG_SECTION="x11/driver"
PKG_SHORTDESC="Generic Xorg Linux input driver"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
