#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.14.0

PKG_DEPENDS="libxfce4ui libwnck libSM"
PKG_MAINTAINER="Benedikt Meurer <benny@xfce.org>, et al"
PKG_SECTION="xfce4"
PKG_SHORTDESC="xfce4 session manager"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      LDFLAGS="$LDFLAGS -Wl,-rpath-link=$INSTALL_PATH/usr/lib -lxcb -lXau -luuid" \
      ac_cv_func_malloc_0_nonnull=yes

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
