#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.14.0

PKG_DEPENDS="exo libwnck garcon"
PKG_MAINTAINER="Nick Schermer <nick@xfce.org>"
PKG_SECTION="xfce4"
PKG_SHORTDESC="xfce4 panel"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      LDFLAGS="$LDFLAGS -luuid -Wl,-rpath-link=$INSTALL_PATH/usr/lib" \
      --disable-gtk2

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
