#!/bin/bash

PKG_NAME=$1
PKG_VERSION=0.8.8

PKG_DEPENDS="exo garcon libwnck"
PKG_MAINTAINER="Benedikt Meurer <benny@xfce.org>, et al"
PKG_SECTION="xfce4"
PKG_SHORTDESC="xfce4 terminal"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
