#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.14.0

PKG_DEPENDS="garcon"
PKG_MAINTAINER="Jannis Pohlmann <jannis@xfce.org>, et al"
PKG_SECTION="xfce4"
PKG_SHORTDESC="xfce4 Find applications applet"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      LDFLAGS="$LDFLAGS -Wl,-rpath-link=$INSTALL_PATH/usr/lib"

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
