#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.4.3

PKG_DEPENDS=""
PKG_MAINTAINER="François Le Clainche <fleclainche at wanadoo.fr>"
PKG_SECTION="xfce4"
PKG_SHORTDESC="xfce4 icon theme"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
