#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.14.1

PKG_DEPENDS="libxfce4util"
PKG_MAINTAINER="Stephan Arts <stephan@xfce.org>, Brian J. Tarricone <bjt23@cornell.edu>"
PKG_SECTION="xfce4"
PKG_SHORTDESC="Xfce4 configures"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
