#!/bin/bash

PKG_NAME=$1
PKG_VERSION=4.10.0

PKG_DEPENDS=""
PKG_MAINTAINER="Olivier Fourdan <fourdan@xfce.org>"
PKG_SECTION="xfce4"
PKG_SHORTDESC="XFCE4 themes"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
