#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.30

PKG_DEPENDS=""
PKG_MAINTAINER="Sergey Udaltsov <svu@users.sourceforge.net>"
PKG_SECTION="x11/data"
PKG_SHORTDESC="X keyboard extension data files"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
