#!/bin/bash

PKG_NAME=$1
PKG_VERSION=7.0.31

PKG_DEPENDS=""
PKG_MAINTAINER="Adam Jackson <ajax@redhat.com>"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="X11 extension headers"

buildpkg() {
  TARGET_CONFIGURE_OPTS=$(echo ${TARGET_CONFIGURE_OPTS}|sed "s/aarch64-/arm-/")
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
