#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.4.0

PKG_DEPENDS=""
PKG_MAINTAINER="Keith Packard <keithp@keithp.com>"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="Abstract network code for X."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
