#!/bin/bash

PKG_NAME=$1
PKG_VERSION=5.2.4

PKG_DEPENDS=""
PKG_MAINTAINER="Lasse Collin <lasse.collin@tukaani.org>"
PKG_SECTION="compress"
PKG_SHORTDESC="A free general-purpose data compression software with high compression ratio."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
