#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.2.11

PKG_DEPENDS=""
PKG_MAINTAINER="Jean-loup Gailly(jloup@gzip.org), Mark Adler(madler@alumni.caltech.edu)"
PKG_SECTION="compress"
PKG_SHORTDESC="A general purpose (ZIP) data compression library"

buildpkg() {
  CC=${TARGET_PREFIX}gcc ../configure --prefix=/usr --shared

  make $MAKEFLAGS
  make install DESTDIR=$INSTALL_PKG
}
